#数据源配置
spring:
  datasource:
    # MySql
    url: jdbc:mysql://localhost:3306/zhisuanx_flow?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
    username: root
    password: root
    # PostgreSQL
    #url: jdbc:postgresql://127.0.0.1:5432/zhisuanx_flow
    #username: postgres
    #password: 123456
    # Oracle
    #url: jdbc:oracle:thin:@127.0.0.1:1521:orcl
    #username: ZHISUANX_FLOW
    #password: oracle
